// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeaceHomeEstateManagement.Context;

#nullable disable

namespace PeaceHomeEstateManagement.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250304115145_newChange")]
    partial class newChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.Amenities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.AmenitiesProperty", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AmenitiesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PropertyId", "AmenitiesId");

                    b.HasIndex("AmenitiesId");

                    b.ToTable("AmenitiesProperties");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PropertyTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.PropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a8ce797-07fa-4e6c-a320-b0260e278e53"),
                            Email = "peacehome@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$lYBER1rYiw3V3.YuynjFgOSvDUqal.Zm/FElKaewGZaYv/qhdNm7q"
                        });
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.AmenitiesProperty", b =>
                {
                    b.HasOne("PeaceHomeEstateManagement.Models.Amenities", "Amenities")
                        .WithMany("AmenitiesProperties")
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeaceHomeEstateManagement.Models.Property", "Property")
                        .WithMany("AmenitiesProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenities");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.Property", b =>
                {
                    b.HasOne("PeaceHomeEstateManagement.Models.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.Amenities", b =>
                {
                    b.Navigation("AmenitiesProperties");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.Property", b =>
                {
                    b.Navigation("AmenitiesProperties");
                });

            modelBuilder.Entity("PeaceHomeEstateManagement.Models.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
